DROP TABLE IF EXISTS IRRIGATION;
DROP TABLE IF EXISTS PLOT_LAND;
DROP TABLE IF EXISTS IRRIGATION_LANDS;



CREATE TABLE IRRIGATION(
  id VARCHAR(250)  PRIMARY KEY,
  irrigation_time_slot  VARCHAR(250) NOT NULL,
  description VARCHAR(250) NOT NULL 
);

CREATE TABLE PLOT_LAND(
  id VARCHAR(250)  PRIMARY KEY,
  PLOT_NAME VARCHAR(250) NOT NULL,
  PLOT_WIDTH  VARCHAR(250) NOT NULL,
  PLOT_LONGITUDE VARCHAR(250) NOT NULL,
  PLOT_LATITUDE VARCHAR(250) NOT NULL,
  PLOT_HEIGHT VARCHAR(250) NOT NULL,
  water_amount VARCHAR(250) NOT NULL,
  START_TIME VARCHAR(250) NOT NULL,
  DURATION_IN_MINUTES VARCHAR(250) NOT NULL
 
);

CREATE TABLE IRRIGATION_LANDS(
  IRRIGATION_ID BIGINT NOT NULL,
  LANDS_ID BIGINT NOT NULL
);
